# SwiftLint Configuration for ViewFeature
# Ultra-Think code quality and consistency standards
# Based on proven HttpClient configuration with ViewFeature-specific optimizations

# Directories and files to lint
included:
  - Sources/
  - Tests/
  - Examples/

# Directories and files to exclude from linting
excluded:
  - .build/
  - .swiftpm/
  - Package.swift
  - Examples/DemoApp/.build/  # Exclude external build dependencies
  - Examples/DemoApp/Examples/Examples/  # Example files may have intentionally simplified code
  - Examples/ControlActionExample/  # Example with Japanese comments for demonstration
  - .claude/
  - "**/swift-syntax/**"  # Exclude swift-syntax external library
  - "**/checkouts/**"     # Exclude SPM checkouts
  - Tests/TestFixtures.swift  # Test fixtures have intentionally simplified code

# Configure specific rules
disabled_rules:
  - todo # We manage TODOs through Claude Code workflow
  - line_length # ViewFeature uses comprehensive documentation requiring flexibility
  - discouraged_none_name # .none is a valid pattern for ActionTask and StoreTask
  - orphaned_doc_comment # Allow flexible doc comment placement
  - multiline_arguments # Allow flexible argument formatting in tests
  - multiline_parameters # Allow flexible parameter formatting
  - let_var_whitespace # Allow compact variable declarations in tests
  - force_unwrapping # Tests may use force unwrapping for simplicity

# Enable opt-in rules for ultra-think code quality
opt_in_rules:
  - comment_spacing
  - empty_count
  - explicit_init
  - implicit_return
  - modifier_order
  - sorted_imports
  - strict_fileprivate
  - unavailable_function
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_assert
  - empty_xctest_method
  - first_where
  - flatmap_over_map_reduce
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_function_chains
  - multiline_literal_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Ultra-Think custom rules for ViewFeature excellence
custom_rules:
  # Note: Japanese comment detection temporarily disabled due to regex false positives
  # Will be re-enabled once regex is refined
  # japanese_doc_comments:
  #   name: "Japanese Documentation Comments"
  #   regex: '///.*[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FAF]'
  #   message: "Documentation comments must be in English only for international collaboration"
  #   severity: warning

  # japanese_inline_comments:
  #   name: "Japanese Inline Comments"
  #   regex: '//[^/].*[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FAF]'
  #   message: "Inline comments must be in English only for international collaboration"
  #   severity: warning

  # japanese_block_comments:
  #   name: "Japanese Block Comments"
  #   regex: '/\*.*[\u3040-\u309F\u30A0-\u30FF\u4E00-\u9FAF].*\*/'
  #   message: "Block comments must be in English only for international collaboration"
  #   severity: warning

  # ViewFeature-specific: Recommend @MainActor usage for UI-related classes
  # Temporarily disabled due to false positives with already annotated classes
  # mainactor_for_ui_classes:
  #   name: "MainActor for UI Classes"
  #   regex: 'class\s+\w*(?:View|Store|Feature|Handler)\w*(?:\s*:\s*[^{]*)?\s*\{'
  #   message: "Consider annotating UI-related classes with @MainActor for thread safety"
  #   severity: warning

  # ViewFeature-specific: Prefer ActionTask over StoreTask in public APIs
  # Temporarily disabled due to regex false positives with StoreFeature
  # prefer_actiontask:
  #   name: "Prefer ActionTask"
  #   regex: 'public.*\bStoreTask\b'
  #   message: "Use ActionTask instead of StoreTask in public APIs for better abstraction"
  #   severity: warning

  # ViewFeature-specific: Ensure proper ultra-think naming
  ultrathink_naming:
    name: "Ultra-Think Naming Convention"
    regex: '(ultra[ _-]?think|ultrathink)'
    message: "Use consistent 'Ultra-Think' naming (capitalized with hyphen)"
    severity: warning

# Rule configurations optimized for ViewFeature architecture
comment_spacing:
  severity: warning

line_length:
  warning: 130  # Slightly longer for comprehensive ViewFeature documentation
  error: 160
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 1100  # Generous limit for comprehensive ViewFeature files and tests
  error: 2000    # Allow for complex test files and specialized components

function_body_length:
  warning: 80   # ViewFeature emphasizes smaller, focused functions
  error: 150

type_body_length:
  warning: 700  # Generous limit for comprehensive test classes and feature implementations
  error: 1000   # ViewFeature may have complex types with extensive test coverage

cyclomatic_complexity:
  warning: 15   # ViewFeature ActionHandlers should be simpler
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 4    # ViewFeature uses more declarative patterns
    error: 8

# Identifier naming rules optimized for ViewFeature patterns
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 45
    error: 80
  excluded:
    - id
    - ID
    - url
    - URL
    - uri
    - URI
    - srp     # Single Responsibility Principle abbreviation
    - ui      # User Interface abbreviation
    - api     # Application Programming Interface abbreviation

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 45
    error: 80
  excluded:
    - SRP     # Single Responsibility Principle

# Function parameter naming
function_parameter_count:
  warning: 5
  error: 8

# Large tuple warning
large_tuple:
  warning: 3
  error: 4

# Multiple closures with trailing closure
multiple_closures_with_trailing_closure:
  severity: warning

# Reporter configuration for ViewFeature development
reporter: "xcode" # Use 'json' for CI/CD integration

# Analysis configuration for advanced Swift 6.0 features
analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration