name: Label PR

on:
  pull_request:
    types: [opened, edited, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  label:
    name: Auto Label PR
    runs-on: ubuntu-latest
    steps:
      - name: Label based on PR title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title.toLowerCase();
            const labels = [];

            // Feature detection
            if (title.includes('feat') || title.includes('feature') || title.includes('add')) {
              labels.push('feature');
            }

            // Bug detection
            if (title.includes('fix') || title.includes('bug')) {
              labels.push('bug');
            }

            // Documentation detection
            if (title.includes('doc') || title.includes('readme')) {
              labels.push('documentation');
            }

            // Refactor detection
            if (title.includes('refactor') || title.includes('cleanup')) {
              labels.push('refactor');
            }

            // Test detection
            if (title.includes('test')) {
              labels.push('test');
            }

            // Performance detection
            if (title.includes('perf') || title.includes('performance') || title.includes('optim')) {
              labels.push('performance');
            }

            // Breaking change detection
            if (title.includes('breaking') || title.includes('!')) {
              labels.push('breaking-change');
            }

            // Maintenance detection
            if (title.includes('chore') || title.includes('maintenance') || title.includes('deps')) {
              labels.push('maintenance');
            }

            // Security detection
            if (title.includes('security') || title.includes('vuln')) {
              labels.push('security');
            }

            // Apply labels if any were found
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labels
              });

              console.log(`Applied labels: ${labels.join(', ')}`);
            } else {
              console.log('No matching labels found');
            }
